### ISSUE TITLE
PulseTime created wrong

### ISSUE THREAD

**Issue by kurt4160** [ioBroker/ioBroker.sonoff#106]
When I set the command "PulseTime1 400" in the console of a Sonoff, the following object is created in Tasmota < 6.7:

"PulseTime1" with the value "400 (active 400)"

With version 6.7. of Tasmota the following object ist created:

"PulsTime1_Set" with the value "400"

Changing the value "PulseTime1_Set" creates a "Command: Unknown" on the Sonoff

**Comment by kurt4160** [comment]
I just found the change in Tasmota:

[https://github.com/arendst/Tasmota/issues/6519](https://github.com/arendst/Tasmota/issues/6519)

Could this be fixed in the adapter?

**Comment by mczeus** [comment]
Es gibt auch ein Pulsetime_remaining der leider nicht aktualisiert wird im Adapter das wäre noch toll um drauf reagieren zu können!

**Comment by sunfingerde** [comment]
I have the same issue but not sure who is responsible for.
Indeed tasmota has changed PulseTime. If you install a new device you will get PulseTime_set and PulseTime_remaining. But you can't control PulseTime_set - tasmota delivers "unknown command".
I haven't had time for debugging but from my feeling tasmota is sending updates on PulseTime_set but only accept PulseTime for setting.
Workaround is setting up manually an object "PulseTimeX" and control it. In case you want check setting you have to ask "PulseTimeX_set" instead.
I have asked tasmota for help but probably I speak another language - nobody understand me.

**Comment by kurt4160** [comment]
Any news on fixing this bug? I don't think tasmote will revert the change:

_Pardon my ignorance if I'm wrong, but I'm not aware of any tools for Tasmota that use this information, so no backwards compatibility would be broken should my request be applied in the code base (October 2019)_

**Comment by tsunfinger** [comment]
Who is responsible for the bug? My personal feeling pointing to Tasmota?

**Comment by kurt4160** [comment]
It was a breaking change in Tasmota. They thought nobody uses this feature over the API. As I said, I don't think Tasmota will undo.

**Comment by tsunfinger** [comment]
And why to hell they are so arrogant when contacting them?

**Comment by ascillato** [comment]
Hi,

> And why to hell they are so arrogant when contacting them?

Please, when you chat in the Tasmota Discord Chat or in the Tasmota Github issues, you are talking with a lot of people of the community and not only the devs. Sorry if you have received arrogant comments. Not everyone have "people skills", but everyone is there because they want to help as free volunteer. No one in Tasmota is getting paid or have any patreon support. We are doing this just for fun, in our free time and because we want.

Going back to this issue:

The commands `PulseTime_set` and `PulseTime_remaining` were never Tasmota commands, so seems that for using those, a forked version of Tasmota was required ? Or those are commands related to the IOBROKER adapter ? 

The related Tasmota issue linked here shouldn't make a breaking change to IOBROKER adapter, due to the actual change in `pulsetime` command was just the JSON output. The new JSON output is a valid parseable JSON that contains all the pulsetimer's times if used as `pulsetime` without specifying which timer you want (this wasn't used by the IOBROKER adapter). **And the output that was used by the IOBROKER adapter (`pulsetimeX`, where X is the number of pulsetimer), was remained intact.** See the console output in Tasmota for those cases:

* Used by the adapter:
```yaml
09:38:16 CMD: pulsetime1
09:38:16 MQT: stat/frente/RESULT = {"PulseTime1":{"Set":1900,"Remaining":0}}
```
* Added and not used by the adapter:
```yaml
09:38:25 CMD: pulsetime
09:38:25 MQT: stat/frente/RESULT = {"PulseTime1":{"Set":1900,"Remaining":0},"PulseTime2":{"Set":1900,"Remaining":0},"PulseTime3":{"Set":0,"Remaining":0},"PulseTime4":{"Set":0,"Remaining":0},"PulseTime5":{"Set":0,"Remaining":0},"PulseTime6":{"Set":0,"Remaining":0},"PulseTime7":{"Set":0,"Remaining":0},"PulseTime8":{"Set":0,"Remaining":0}}
```

The second output was the one added in the Tasmota request https://github.com/arendst/Tasmota/issues/6519

In order to help on this from Tasmota side, we need more information like console outputs, commands used and how the IOBROKER adapter works in order to have something to work on. Thanks.

**Comment by kurt4160** [comment]
Any chance of fixing this in the adapter. I have to stay on Tasmota 6 because of this issue.

**Comment by tsunfinger** [comment]
As you can see - it's already closed. I guess it won't be fixed.

**Comment by kurt4160** [comment]
> As you can see - it's already closed. I guess it won't be fixed.

The Tasmota issue is closed and I aggre with you, that this won't get fixed. But I meant the iobroker adapter issue. This issue is still open.
