### ISSUE TITLE
Wrong typ nach Umstellung auf js-controller 3.3.4

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.sonoff#178]
lt. Community sollen Meldungen die sich aus der Umstellung des js-controller auf die Version 3.3.4 ergeben bei den entsprechenden Adaptern gemeldet werden.

Der Adapter funktioniert Augenscheinlich normla, jedoch wird das LOG mit WARN Meldungen übersäät.

![image](https://user-images.githubusercontent.com/44617472/116776319-132d7900-aa68-11eb-9643-1fab5099ff26.png)

**Comment by itProfi** [comment]
same problem on js-controller 3.3.16
![Скриншот 01-05-2021 114019](https://user-images.githubusercontent.com/6728198/116776726-c8652e80-aa72-11eb-8c0b-40b56a3a8c74.jpg)
![Скриншот 01-05-2021 113947](https://user-images.githubusercontent.com/6728198/116776728-c8fdc500-aa72-11eb-9119-91d2c80e1a97.jpg)
![Скриншот 01-05-2021 113319](https://user-images.githubusercontent.com/6728198/116776729-c9965b80-aa72-11eb-91f6-7d578522c6ee.jpg)

**Comment by WolfgangGr** [comment]
**Describe the bug**  
After updating of js-controller 3.2.16 to 3.3.2 it will be logged a warning
`2021-04-30 20:13:39.718 - warn: sonoff.0 (3094) State value to set for "sonoff.0.Pow_1.SleepMode" has wrong type "string" but has to be "number"`

**To Reproduce**  
Steps to reproduce the behavior:
Update to js-controller 3.3.2

**Expected behavior**  
no warning

**Screenshots & Logfiles**  
`2021-04-30 20:13:39.718 - warn: sonoff.0 (3094) State value to set for "sonoff.0.Pow_1.SleepMode" has wrong type "string" but has to be "number"
2021-04-30 20:13:39.748 - warn: sonoff.0 (3094) State value to set for "sonoff.0.Pow_1.Wifi_SSId" has wrong type "string" but has to be "number"
2021-04-30 20:13:39.751 - warn: sonoff.0 (3094) State value to set for "sonoff.0.Pow_1.Wifi_BSSId" has wrong type "string" but has to be "number"
2021-04-30 20:13:39.754 - warn: sonoff.0 (3094) State value to set for "sonoff.0.Pow_1.Wifi_Channel" has wrong type "number" but has to be "string"
2021-04-30 20:13:39.763 - warn: sonoff.0 (3094) State value to set for "sonoff.0.Pow_1.Wifi_Downtime" has wrong type "string" but has to be "number"
2021-04-30 20:13:39.768 - warn: sonoff.0 (3094) State value to set for "sonoff.0.Pow_1.ENERGY_TotalStartTime" has wrong type "string" but has to be "number"`

**Versions:**  
 - Adapter version: <2.4.0>
 - JS-Controller version: <3.3.2>
 - Node version: <12.22.1>
 - Operating system: <Raspian buster 10>

**Comment by Matt77CHE** [comment]
... same to me

**Comment by FoRealx** [comment]
same here.

**Comment by nemodil** [comment]
same for me with tasmota 9.4.0.3 

sonoff.0 | 2021-05-02 17:12:25.524 | info | (1793) State value to set for "sonoff.0.DVES_9289DD.Wifi_Downtime" has to be type "number" but received type "string"
sonoff.0 | 2021-05-02 17:12:25.506 | info | (1793) State value to set for "sonoff.0.DVES_9289DD.Wifi_Channel" has to be type "string" but received type "number"
sonoff.0 | 2021-05-02 17:12:25.501 | info | (1793) State value to set for "sonoff.0.DVES_9289DD.Wifi_BSSId" has to be type "number" but received type "string"
sonoff.0 | 2021-05-02 17:12:25.495 | info | (1793) State value to set for "sonoff.0.DVES_9289DD.Wifi_SSId" has to be type "number" but received type "string"
sonoff.0 | 2021-05-02 17:12:25.446 | info | (1793) State value to set for "sonoff.0.DVES_9289DD.LedTable" has to be type "number" but received type "string"
sonoff.0 | 2021-05-02 17:12:25.366 | info | (1793) State value to set for "sonoff.0.DVES_9289DD.SleepMode" has to be type "number" but received type "string"

**Comment by Apollon77** [comment]
Can someone please show the values? SO a screenshot from admin with state values of such affected states. we need to see if the definition is wrong or the data needs tobe converted or such

**Comment by nemodil** [comment]
![screenshot](https://user-images.githubusercontent.com/45435219/116819517-a8b43000-ab70-11eb-9893-d7486b3028ef.jpg)

**Comment by nemodil** [comment]
![screenshot2](https://user-images.githubusercontent.com/45435219/116819612-16f8f280-ab71-11eb-9384-39fdaade370a.jpg)

**Comment by nemodil** [comment]
18:08:19.392 MQT: tele/tasmota_0912A7/STATE = {"Time":"2021-05-02T18:08:19","Uptime":"0T03:15:43","UptimeSec":11743,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":11,"POWER":"ON","Wifi":{"AP":1,"SSId":"Skynet","BSSId":"3C:A6:2F:23:6A:94","Channel":6,"RSSI":52,"Signal":-74,"LinkCount":1,"Downtime":"0T00:00:07"}}

**Comment by andiweli** [comment]
Still "...has to be number but received string" with JS-Controller 3.3.8 - but "info" instead of "warn"...

`
(24564) State value to set for "sonoff.0.Pool.ENERGY_TotalStartTime" has to be type "number" but received type "string"
--
sonoff.0 | 2021-05-05 08:36:57.341 | info | (24564) State value to set for "sonoff.0.Pool.Wifi_Downtime" has to be type "number" but received type "string"
sonoff.0 | 2021-05-05 08:36:57.307 | info | (24564) State value to set for "sonoff.0.Pool.Wifi_Channel" has to be stringified but received type "number"
sonoff.0 | 2021-05-05 08:36:57.297 | info | (24564) State value to set for "sonoff.0.Pool.Wifi_BSSId" has to be type "number" but received type "string"
sonoff.0 | 2021-05-05 08:36:57.247 | info | (24564) State value to set for "sonoff.0.Pool.Wifi_SSId" has to be type "number" but received type "string"
sonoff.0 | 2021-05-05 08:36:57.107 | info | (24564) State value to set for "sonoff.0.Pool.SleepMode" has to be type "number" but received type "string"
`

**Comment by Flyor** [comment]
Ist zwar mittlerweile nur noch eine "Info", aber ich bekomm das Log trotzdem damit zugeknallt. 
![image](https://user-images.githubusercontent.com/64526892/117126019-87368c80-ad9a-11eb-8513-2830742e7327.png)
WiFi Channel sind eigentlich nur Zahlen, ich weiß nicht warum er denkt es sei ein String. 
![image](https://user-images.githubusercontent.com/64526892/117126183-b3eaa400-ad9a-11eb-9245-d883e4375e44.png)

**Comment by markusfalcone** [comment]
Is there already a solution?

**Comment by Apollon77** [comment]
Set loglevel of adapter to warning and you do not see these logs ... are just warnings

**Comment by Flyor** [comment]
> Set loglevel of adapter to warning and you do not see these logs ... are just warnings

That's killing of side effects and no solution for the problem... If there will be a solution in the future and that should be to bridge the time, it's ok for me. But not as an end result.

**Comment by Apollon77** [comment]
Yes there will be a solution ... or you provide a PR so it's getting faster.

**Comment by msiemers** [comment]
Wann wird es eine Lösung für die ständigen Log Einträge geben. Ich habe das Gefühl das mir die ständigen Einträge immer den Swap voll machen. Danke

**Comment by Apollon77** [comment]
Sobald jemand dazu kommt wird es ggf eine Lösung geben. Als Zwischenloösung einfach Loglevel der Instanz auf "warn" stellen

**Comment by GermanBluefox** [comment]
Please test 2.4.1

**Comment by Matt77CHE** [comment]
Ok, wollte die 2.4.1 testen - 
wo finde ich die? - 
Bin auf beta-Kanal, auf github kann ich nur die 2.4.0 finden; auch wenn ich den Link kopiere ist es die 2.4.0

**Comment by GermanBluefox** [comment]
Geduld: gerade wird die Version gebaut - https://github.com/ioBroker/ioBroker.sonoff/actions/runs/1040007692
Dann um 14 wird neues Repo gebaut. Danach sieht man die Version in Admin (nachdem man auf "refresh" Knopf lickt)

**Comment by Matt77CHE** [comment]
ok, ist jetzt online- habe sie installiert. Ist nun viel besser!
Was ich im Log noch habe:
![sonoff](https://user-images.githubusercontent.com/73795309/126032796-4357ac92-d782-4ee4-a1c3-f8ad4e6470e1.JPG)

**Comment by Matt77CHE** [comment]
![sonoff_2](https://user-images.githubusercontent.com/73795309/126032841-1b487ffe-b4cb-4ffb-b5d5-8458f25e2ae9.JPG)

**Comment by GermanBluefox** [comment]
Please test 2.4.2

**Comment by Matt77CHE** [comment]
Vielen Dank; 
habe die 2.4.2 installiert - bis jetzt keine Meldungen mehr über State value.
