### ISSUE TITLE
Doesn't send update to Sonoff

### ISSUE THREAD

**Issue by Leseratte10** [ioBroker/ioBroker.sonoff#20]
I am using this plugin to connect my Sonoff to ioBroker, and I have a second MQTT broker instance (on another port) in ioBroker. When I click the sonoff POWER value under "objects" and change its value, the sonoff switches. If I change "sonoff/0/devicename/POWER" using a mqtt client, the value in the objects table changes, but the sonoff doesn't switch. 

Why is that? Is that a problem with the sonoff plugin or with the mqtt broker plugin?

**Comment by GermanBluefox** [comment]
As far as i understand, sonoff works and mqtt not.
Why you write the issue in sonoff?

Sonoff expects as value the json.

Am 05.02.2018 22:04 schrieb "Leseratte10" <notifications@github.com>:

I am using this plugin to connect my Sonoff to ioBroker, and I have a
second MQTT broker instance (on another port) in ioBroker. When I click the
sonoff POWER value under "objects" and change its value, the sonoff
switches. If I change "sonoff/0/devicename/POWER" using a mqtt client, the
value in the objects table changes, but the sonoff doesn't switch. Why is
that?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ioBroker/ioBroker.sonoff/issues/20>, or mute the thread

**Comment by Jetiman** [comment]
Hi,

ich habe das selbe Problem.
Nutze für andere Objekte den MQTT Server Adapter.
Nur für die Sonoff den sonoff Adapter.

Wenn ich nun über den MQTT Server eine Sonoff status z.b auf true setze steht im iobrocker auch true, aber der sonoff schaltet nicht. Wenn ich true direkt im iobrocker schreibe schaltet er.

**Comment by GermanBluefox** [comment]
In process: https://github.com/gemu2015/iobroker-sonoff-test

Duplicate to https://github.com/ioBroker/ioBroker.sonoff/issues/29

**Comment by xcashy** [comment]
Ist zwar schon was älter, aber ich hatte auch das Problem.
Ihr müsst als MQTT message, wie GermanBluefox bereits erwähnte,  ein json objekt senden.
Zum Beispiel: topic = 'sonoff.0.lampe.POWER', message = '{"val" : "true"}'
