### ISSUE TITLE
Automatic creation of objects no longer works correctly

### ISSUE THREAD

**Issue by FabianHM** [ioBroker/ioBroker.sonoff#97]
@gemu2015 
Hello Gerhard,
All at once, the automatic creation of new statuses no longer seems to work properly. I noticed that, for example, at the state "WifiConfig" the value is already used in the name .. see screenshot.

![sonoff](https://user-images.githubusercontent.com/26110738/67161072-41040e80-f357-11e9-947a-ec0e9921225c.JPG)

Furthermore, it can be explained that the "Info" or the State "alive" is no longer transmitted. 
Can the update be based on the JS-Controller 2.0.34 ?
Thank you for your help,

greetings
Fabian

**Comment by gemu2015** [comment]
HI Fabian

i updated my used iobroker adapters today to check your issue.  (but still using js-controller 1.2.3) no impact
since my broker works fine for my purposes i dont wont to update js-controller now and my focus currently is on other projects
since js-controller was heavily modified this could be the cause of your failure.
there is another issue indicating this. (https://github.com/ioBroker/ioBroker.sonoff/issues/96 <https://github.com/ioBroker/ioBroker.sonoff/issues/96>)
from tasmota side i can not see an json issues that may cause this.


Gerhard

**Comment by GermanBluefox** [comment]
@FabianHM Do you have a JSON that produced such a strange state (WifiConfg_4)?

**Comment by FabianHM** [comment]
Unfortunately not. I have now deleted the faulty WifiConfig_4 State. The assumption was that the status was new and correctly transferred, but that is not the case. The folder missing folder "Info" has now apparently been transferred.... I dont' undestand what happend

**Comment by GermanBluefox** [comment]
I assume, that sonoff could send wrong data too. I have tests in the adapter and all of them are green.

**Comment by kurt4160** [comment]
For me this happens with Tasmota 6.7. I downgraded to 6.6. and it works again.

**Comment by merlin2533** [comment]
Restart of the adapter helps to regenerte it
